services:
  - type: web
    name: mini-project-i
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: rzp_test_SGr3TtEdPGJPpf
      - key: RAZORPAY_KEY_SECRET
        value: 8j3b0VhFxCNkiTm7Azd7WHrC
